### ISSUE TITLE
Incorrect file size & length for files over 2gb

### ISSUE THREAD

**Issue by Paladin-z** [DukeLupus/QuickList#2]
When making a list with content over 2gb per file the wrong size and length is shown in the list even with ForceShellMedia=1.
e.g
Ant-Man (2015).mkv is **2.95gb 1:57:06** but listed as **1.05GB 57m06s**
Avengers Age of Ultron (2015).mkv is **3.56gb 2:21:18** but listed as **449.66MB 21m18s**
The Avengers (2012).mp4 is **3.51gb 2:22:54** but listed as **497.03MB 22m54s**

**Comment by SanderSade** [comment]
Good catches, thank you. 

The size is due to incomplete handling of file size ([nFileSizeLow](https://github.com/DukeLupus/QuickList/blob/b50e4db87ffb4d5b944ef5d54e3c72cb5f79b583/QuickList/Application/FileReader.cs#L218)) and easy to fix - quickfix hopefully within a few days.

On media info, I have to see what is going on. It is weird that even with ForceShellMedia=1 the same issue persists - did both 0 and 1 give the same duration?  I wonder if the mkv/mp4 containers have other tracks in it, and the media routines just pick up the first, which happens to be invalid/not the main media?

**Comment by Paladin-z** [comment]
A friend on Undernet brought it to my attention, my list didn't contain large files but his did. As he was using an older quicklist I did a test list on my machine with the latest quicklist to confirm it.

After testing there is no difference between using ForceShellMedia=1 or 0.

The files I've tested have 1 or 2 audio streams and 1 video stream, none of which match the duration generated by quicklist according to MediaInfo.

Testing it with a 6.69gb .zip file QuickList shows it as 1.3GB so it doesn't correlate to media content.

**Comment by SanderSade** [comment]
[This commit](https://github.com/DukeLupus/QuickList/commit/4dab5fbc2646fea95f7b97816d4a0d08adf4125c) fixes the file size problem. I have hard time repeating the media duration bug - I'll try to get some more files to test with, and will do a release once I can track that problem down.

**Comment by SanderSade** [comment]
NVM, I can repeat it now. What threw me off was that [DirLister](https://github.com/SanderSade/DirLister) which has a lot of the same code, had the size bug but showed the durations correctly. I have to figure out what is different between their media info implementations.

**Comment by SanderSade** [comment]
I've released [beta 6](https://github.com/DukeLupus/QuickList/releases/tag/v3-beta.6).

Can you please especially look for inconsistencies in the media duration - the time-to-string formatting was really off before, but is hopefully better now. You'll have to check "Delete media info cache" or delete MediaCache.ql3 manually, or you'll get the old cached duration.

When testing, I managed to freeze the listmaker once with a very large file (40GB) during media info gathering, but was unable to repeat it. Could have been an issue with the network (the movie was on a network drive), or could be something else. I tried quite a few times after and it worked fine...

**Comment by SanderSade** [comment]
Resolving, seems to be working
