### ISSUE TITLE
Incorrect file size & length for files over 2gb

### ISSUE THREAD

**Issue by DukeLupus** [DukeLupus/QuickList#3]
Submitter: AbueIo
Email: abueio@hotmail.es
When making a list with content over 2gb per file the wrong size and length is shown in the list even with ForceShellMedia=1.
e.g
Ant-Man (2015).mkv is 2.95gb 1:57:06 but listed as 1.05GB 57m06s
Avengers Age of Ultron (2015).mkv is 3.56gb 2:21:18 but listed as 449.66MB 21m18s
The Avengers (2012).mp4 is 3.51gb 2:22:54 but listed as 497.03MB 22m54s

This is the copy (I have got the same problem), what you have put into https://github.com/DukeLupus/QuickList/issues/2 for Paladinz, from mp3passion.
Thanks a lot for your answer and if it possible fix this problem.

See you and thanks a lot for your great (and very long time) work.

**Comment by Pepillo24** [comment]
Ohh, sorry a lot.. just don't read the last answer :(
Sorry if I repeat!!

**Comment by SanderSade** [comment]
Copy of issue https://github.com/DukeLupus/QuickList/issues/2 - closing this one.

Thank you for reporting, though!
