### ISSUE TITLE
Version 3 Beta.6 is a complete success !!!! Thanks!!!!

### ISSUE THREAD

**Issue by Pepillo24** [DukeLupus/QuickList#4]
Hello SanderSade, just in this moment I made a probes... and this is the results....
I made with V3 Beta 5, second probe with V3 Beta 6 (Only Size), and 3rd probe with (Mediainfo)

Paste the results, and You made a Great, Great Work!!!+Thanks a lot.

TEST
================================
QuickList V.3 Beta5  (Only Size On, Mediainfo OFF)

HEADER: 

OmeNServE v2.60
List of 5,062 Files (574GB)

In this case: I had the actual size written between (X_XXGiB) since, as you can see, quicklist did not recognize it, so that it really knew what the file occupied.

EG:
!QuitNick Notting Hill (1999)_1080p_(x264_Esp_Eng&Subti)(4_97GiB).mkv ::INFO:: 999.95MB
!QuitNick Oblivion (2013)_1080p_(x264_Esp_Eng&Subti)(5_87GiB).mkv ::INFO:: 1.88GB
!QuitNick Okja (2017)_1080p_(x264_AC3_Esp_Eng&Subti)(4_23GiB).mkv ::INFO:: 241.62MB
!QuitNick Pacific Rim (2013)_1080p_(x264_Esp_Eng&Subti)(6_04GiB).mkv ::INFO:: 1.95GB

================================================================================================

QuickList V.3 Beta6 (Select Include File Size)

HEADER: 

OmeNServE v2.60
List of 5,085 Files (3.67TB) (Good Diference)

EG:
!QuitNick Notting Hill (1999)_1080p_(x264_Esp_Eng&Subti)(4_97GiB).mkv ::INFO:: 4.98GB
!QuitNick Oblivion (2013)_1080p_(x264_Esp_Eng&Subti)(5_87GiB).mkv ::INFO:: 5.88GB
!QuitNick Okja (2017)_1080p_(x264_AC3_Esp_Eng&Subti)(4_23GiB).mkv ::INFO:: 4.24GB
!QuitNick Pacific Rim (2013)_1080p_(x264_Esp_Eng&Subti)(6_04GiB).mkv ::INFO:: 6.05GB

VERY GOOD, FIXED SIZE PROBLEM!!!!!!!!!!!

====================================================================================

QuickList V.3 Beta5 (Select Include MediaInfo)

HEADER: 

OmeNServE v2.60
List of 5,085 Files (3.67TB) (Good Diference)

EG:

!QuitNick Notting Hill (1999)_1080p_(x264_Esp_Eng&Subti)(4_97GiB).mkv ::INFO:: 4.98GB 2h03m57s 1920x1080
!QuitNick Oblivion (2013)_1080p_(x264_Esp_Eng&Subti)(5_87GiB).mkv ::INFO:: 5.88GB 2h04m42s 1920x1088
!QuitNick Okja (2017)_1080p_(x264_AC3_Esp_Eng&Subti)(4_23GiB).mkv ::INFO:: 4.24GB 2h01m21s 1920x804
!QuitNick Pacific Rim (2013)_1080p_(x264_Esp_Eng&Subti)(6_04GiB).mkv ::INFO:: 6.05GB 2h11m18s 1920x1088

wuooo, wuooo, wuoooo, FIXED SIZE AND LENGHT PROBLEMS... Thanks a lot!!! SanderSade

You have just done a job of 2 decades in 2 days.
Thank you very much for your dedication and your effort.

Is a real pleasure said this, the people can update his Omenserve with your new QuickList V.3 Beta6.

**Comment by SanderSade** [comment]
Thank you. Now, if anyone only would update/rewrite OmenServe, it needs that badly...

I will leave this and the other issue open for a while, in case someone finds any problems. I do know that duration will be invalid for media files with duration over 100h, but I am hoping that these are very rare... :P

**Comment by Pepillo24** [comment]
Thank you very much for your effort SanderSade.
I wanted to ask if the improvement also affects ListMagic?
Since as you know, this list generator does give the option of putting the News of the last days, while QuickList does not have the option of News.
Thank you very much for your reply.
I mean lm2.exe
Thank you very much and ... by God I hope there are no files with a duration of more than 100 hours .. NEVER !!! :)
Have a nice day!! And thank you very much for everything.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Sander Säde <notifications@github.com>
Enviado: Friday, July 26, 2019 9:17:39 AM
Para: DukeLupus/QuickList <QuickList@noreply.github.com>
Cc: Pepillo24 <abueio@hotmail.es>; Author <author@noreply.github.com>
Asunto: Re: [DukeLupus/QuickList] Version 3 Beta.6 is a complete success !!!! Thanks!!!! (#4)


Thank you. Now, if anyone only would update/rewrite OmenServe, it needs that badly...

I will leave this and the other issue open for a while, in case someone finds any problems. I do know that duration will be invalid for media files with duration over 100h, but I am hoping that these are very rare... :P

**Comment by Paladin-z** [comment]
Tested with my media library also and works perfectly, duration is within 1 second of that shown by Explorer and file sizes are spot on!

**Comment by Pepillo24** [comment]
Certainly, I have compared it to the official version of Mediainfo 19.07 (latest version), and everything works very well.
:)

But do you refer exclusively to Quicklist?
Or are you telling me that ListMagic (the other Omenserve list generator), has also been fixed by updating Quicklist V3 Beta.6 ???

I don't know if it would be convenient to follow this conversation at https://github.com/DukeLupus/QuickList, although we are talking about the other ListMagic list generator, not the one you have already arranged superbly (Quicklist).
Sorry for my English, I'm using the Google translator.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Paladin-z <notifications@github.com>
Enviado: Friday, July 26, 2019 11:42:09 AM
Para: DukeLupus/QuickList <QuickList@noreply.github.com>
Cc: Pepillo24 <abueio@hotmail.es>; Author <author@noreply.github.com>
Asunto: Re: [DukeLupus/QuickList] Version 3 Beta.6 is a complete success !!!! Thanks!!!! (#4)


Tested with my media library also and works perfectly, duration is within 1 second of that shown by Explorer and file sizes are spot on!

**Comment by SanderSade** [comment]
ListMagic is unfortunately closed source, created by mp3oholic - see the [OmenServe history](http://www.statemaster.com/encyclopedia/OmenServe), so it is extremely unlikely that ListMagic will ever get updated.

I don't think mp3oholic has been active in IRC for 12 years or more. If you can find him (good place to start would be Undernet #mp3servers), he might be willing to provide the source for LM....

**Comment by Pepillo24** [comment]
Ohh, I know mp3servers… I’m @ there!!!
Thanks a lot for information, and repeat, repeat, thanks a lot for your Great Work SanderSäde.
Is a pleasure know you!.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Sander Säde <notifications@github.com>
Enviado: Friday, July 26, 2019 12:24:49 PM
Para: DukeLupus/QuickList <QuickList@noreply.github.com>
Cc: Pepillo24 <abueio@hotmail.es>; Author <author@noreply.github.com>
Asunto: Re: [DukeLupus/QuickList] Version 3 Beta.6 is a complete success !!!! Thanks!!!! (#4)


ListMagic is unfortunately closed source, created by mp3oholic - see the OmenServe history<http://www.statemaster.com/encyclopedia/OmenServe>, so it is extremely unlikely that ListMagic will ever get updated.

I don't think mp3oholic has been active in IRC for 12 years or more. If you can find him (good place to start would be Undernet #mp3servers), he might be willing to provide the source for LM....

**Comment by SanderSade** [comment]
#mp3servers used to be Tipi's, and by extension, OmenServe's main channel. I don't think anyone from that era is still active there, though.

**Comment by Pepillo24** [comment]
Ahhh, I understand.. the old web of Omenserve (Tipi’s) #mp3servers.. 😊

Uauuu, a lot time ago!!!! ☹

Thank you very much for your interest and your clarifications.

Have you a nice day SanderSade.

**Comment by SanderSade** [comment]
Resolving, seems to be working
